QuestionSource/config/routes.rb
QuestionSource::Application.routes.draw do
  get "site/about"

  get "site/contact"
  get "home/index"
  
  match '/about' => 'site#about'
  match '/contact' => 'site#contact'

  resources :answers

  resources :questions do
    resources :answers
  end

  resources :sections do
    resources :questions do
      resources :answers
    end
  end

  devise_for :users

  root :to => "home#index"

end

QuestionSource/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :desc, :score, :submitted, :user
  validates_presence_of :desc, :user
end

QuestionSource/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :section
  has_many :answers
  attr_accessible :desc, :name, :score, :submitted, :user, :section
  validates_presence_of :name, :desc
end

QuestionSource/app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :name, :id
  has_many :questions
  validates_presence_of :name
end

QuestionSource/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

QuestionSource/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answers = @question.answers

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @input1 = params[:submit_tag]
    @vote = Vote.runcheck(@input1)
    @answer.score = @answer.score + @vote
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build

  end

  # GET /questions/1/edit
  def edit
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
   def create
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      redirect_to question_answer_url(@question, @answer)
    else
      render :action => "new"
    end
  end
  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to question_answer_url(@question, @answer)
    else
      render :action=>"edit"
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    
    respond_to do |format|
      format.html { redirect_to question_answers_path(@question) }
      format.xml { head :ok }
    end
  end
end

QuestionSource/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

QuestionSource/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

QuestionSource/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @section = Section.find(params[:section_id])
    @questions = @section.questions

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
 
    @section = Section.find(params[:section_id])
    @question = @section.questions.find(params[:id])
    @input1 = params[:submit_tag]
    @vote = Vote.runcheck(@input1)
    @question.score = @question.score + @vote
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @section = Section.find(params[:section_id])
    @question = @section.questions.build

  end

  # GET /questions/1/edit
  def edit
    @section = Section.find(params[:section_id])
    @question = @section.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
   def create
    @section = Section.find(params[:section_id])
    @question = @section.questions.build(params[:question])
    if @question.save
      redirect_to section_question_url(@section, @question)
    else
      render :action => "new"
    end
  end
  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question])
      redirect_to section_question_url(@section, @question)
    else
      render :action=>"edit"
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @section = Section.find(params[:section_id])
    @question = Question.find(params[:id])
    @question.destroy
    
    respond_to do |format|
      format.html { redirect_to section_questions_path(@section) }
      format.xml { head :ok }
    end
  end
end

QuestionSource/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end
end

QuestionSource/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

QuestionSource/app/helpers/answers_helper.rb
module AnswersHelper
end

QuestionSource/app/helpers/application_helper.rb
module ApplicationHelper
end

QuestionSource/app/helpers/home_helper.rb
module HomeHelper
end

QuestionSource/app/helpers/questions_helper.rb
module QuestionsHelper
end

QuestionSource/app/helpers/sections_helper.rb
module SectionsHelper
end

QuestionSource/app/helpers/site_helper.rb
module SiteHelper
end

QuestionSource/app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Your Answer" %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.date_select :submitted, { :discard_day => true, :discard_month => true, :discard_year => true }%>
  </div>
  <div class="field">
    <%= f.hidden_field :score, :value => 10 %>
  </div>
  <% if user_signed_in? %>
  <div class="field">
    <%= f.hidden_field :user, :value => current_user.email%>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Submit Your Answer"%>
  </div>
<% end %>

QuestionSource/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', section_question_answer_path(@section, @question, @answer) %> |
	
<%= link_to 'Back', question_answers_path(@question) %>

QuestionSource/app/views/answers/index.html.erb
<h1> All Answers in <%= @question.name %></h1>
	
<table>
<tr>
</tr><% for answer in @answers %><tr>
<td><%= answer.desc %></td><td> &nbsp;<%= link_to 'View Answer', question_answer_path(@question, answer)%></td>
</tr>

<% end %>
</table>
<br />
		  
<%= link_to 'New Answer', new_section_question_answer_path(@section, @question) %>
<%= link_to 'Back to Question', [@section, @question] %>

QuestionSource/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', section_question_answers_path(@section, @question) %>

QuestionSource/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @answer.desc %>
</p>

<p>
  <b>Submitted:</b>
  <%= @answer.submitted %>
</p>

<p>
  <b>Score:</b>
  <%= @answer.score %>
</p>

<p>
  <b>User:</b>
  <%= @answer.user %>
</p>

<%= link_to 'Back', section_question_answers_path(@section, @question) %>
<% user = current_user.email%>
<% if @question.user == user %>
<%= link_to 'Edit', edit_section_question_answer_path(@section, @question, @answer) %> |
<% end %>

QuestionSource/app/views/home/index.html.erb
<h1>Welcome to Question Source</h1>
<p>A Place to ask and answer all your questions.</p>

QuestionSource/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionSource</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
	<div id="header">
		<h1>Question Source A Place For Answers</h1>
	</div>
	<div id="menu">
		<div id="navbar">
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/sections">Sections</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contact">Contact Us</a></li>
				<li><%= link_to 'Login', new_user_session_path %></li>
				<li><%= link_to 'Register', new_user_registration_path %>
				<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>

			</ul>
		</div>

		</div>
		<div id="container">
			<div id="content">
				<p class="notice"><%= flash[:notice] %></p>
				<%= yield %>
				

			</div>
			<div id="first-column">
				
			</div>
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>

			</div>
		</div>

<div id="footer">
	<h6 class="footertext">&copy; Question Source &trade; 2014</h6>
</div>

</body>
</html>

QuestionSource/app/views/questions/_form.html.erb
<%= form_for([@section, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.date_select :submitted, { :discard_day => true, :discard_month => true, :discard_year => true }%>
  </div>
  <div class="field">
    <%= f.hidden_field :score, :value => 10 %>
  </div>
  <% if user_signed_in? %>
  <div class="field">
    <%= f.hidden_field :user, :value => current_user.email%>
  </div>
  <% else %>
  <div class="field">
    <%= f.hidden_field :user, :value =>"Anonymous" %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

QuestionSource/app/views/questions/edit.html.erb
<h1>Editing Question</h1>
	
<%= render 'form' %>
	
<%= link_to 'Show', section_question_path(@section, @question) %> |
	
<%= link_to 'Back', section_questions_path(@section) %>

QuestionSource/app/views/questions/index.html.erb
<h1> All Questions in <%= @section.name %></h1>
	
<table>
<tr>
</tr><% for question in @questions %><tr>
<td><%= question.name %></td><td> &nbsp;<%= link_to 'View Question', section_question_path(@section, question)%></td>
</tr>

<% end %>
</table>
<br />
		  
<%= link_to 'New Question', new_section_question_path(@section) %>
<%= link_to 'Back to Section', @section %>

QuestionSource/app/views/questions/new.html.erb
<h1>New	Question</h1>	
  
<%= render'form'%>		
<%= link_to 'Back', section_questions_path(@section) %>

QuestionSource/app/views/questions/show.html.erb
<h1>Question in <%= @section.name %></h1>

<p>
  <b>Name:</b>
  <%= @question.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @question.desc %>
</p>

<p>
  <b>Submitted:</b>
  <%= @question.submitted %>
</p>

<p>
  <b>Score:</b>
  <%= @question.score %>
</p>
<p>
	<%= submit_tag 1, :value=>"Up Vote" %> &nbsp;
	<%= submit_tag 2, :value=>"Down Vote" %>
</p>
<p>
  <b>Submitted by:</b>
  <%= @question.user %>
</p>
<h2>Answers in <%= @question.name %></h2>
<% @question.answers.each do |answer| %>
<p>
<b>Answer Details</b>
<%= answer.desc %> &nbsp;<%= link_to 'View Answer', section_question_answer_path(@section, @question, answer)%>
</p>
	
<% end %>

<% if user_signed_in? %>
<%= link_to 'Add An Answer', new_section_question_answer_path(@section, @question)%>
<% user = current_user.email%>
<% if @question.user == user %>
<%= link_to 'Edit', edit_section_question_path(@section, @question) %> |
<%= link_to 'Back', section_questions_path(@section) %>
<% end %>
<% end %>

QuestionSource/app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

QuestionSource/app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

QuestionSource/app/views/sections/index.html.erb
<table>
<% @sections.each do |section| %>
  <tr>
    <td><h2><%= section.name %></h2></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><%= link_to 'See Active Questions', section %></td>
  </tr>
<% end %>
</table>

QuestionSource/app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

QuestionSource/app/views/sections/show.html.erb
<p><b>Section:</b>
<%= @section.name %></p>
		  
<h2>Questions</h2>
<% @section.questions.each do |question| %>
<p>
<b>Question Title:</b>
<%= question.name %> &nbsp;<%= link_to 'View Question', section_question_path(@section, question)%>
</p>
	
<% end %>
<%= link_to 'Ask A New Question', new_section_question_path(@section)%>

QuestionSource/app/views/site/about.html.erb
<div class="inner">
	<h1>About Us</h1>
	<p>This site was developed as part of a final year module project. 
		Many Aspects of the site are to be considered from a development point of view.
		Some practices undertaken, may not be production ready in term of security.
		Please bare with us, as our progress develops.</p>
</div>
<br />
<br />
<div class="lower">
		<table width="100%" cellpadding="3" cellspacing="3">
			<tr>
			<th>Development Location:</th>
			<th>Developed By:</th>
			<th>Development Period:</th>
			</tr>
			<tr>
				<td><h6>Ireland</h6></td>
				<td><h6>Andrew Phelan</h6></td>
				<td><h6>February - April 2014</h6></td>
			</tr>
		</table>
</div>

QuestionSource/app/views/site/contact.html.erb
<h2>Please Direct Any Enquiries to:</h2>

<div>
<h1><a href="/sections/14">The Test Section</a></h2>
</div>